spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TEST_DB?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
